### ISSUE TITLE
DGL and Open Babel Errors

### ISSUE THREAD

**Issue by Lyang556** [baker-laboratory/rf_diffusion_all_atom#1]
Thank you for making this code available! However, I found two errors while running this code, they are
`/opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /opt/conda/envs/env/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.13.1.so: cannot open shared object file: No such file or directory
` 
and 
`*** Open Babel Error  in openLib
  /usr/lib/openbabel/3.1.0/png2format.so did not load properly.
`
`
 Error: libXrender.so.1: cannot open shared object file: No such file or directory.
`

Could you please help me check that if these two errors may affect the results?

Thank you.

**Comment by rhsimplex** [comment]
Hi @Lyang556 I'm not running the code in the Appcontainer, but I was able to fix this by installing  libxrender

`sudo apt-get install libxrender1`

**Comment by Lyang556** [comment]
@rhsimplex  Thank you so much, I've successfully solved these problems and will close this issue.

**Comment by hzy777641** [comment]
@rhsimplex  I found the same errors on my wsl2, but I could not fix it by installing libxrender. It said that libxrender already installed. So, could you please give me some advice,or help me check  if these two errors may affect the results? Thank you.

**Comment by AlvinAi-cloud** [comment]
@hzy777641 Have you solved your issues? I am facing the same issue, but libxrender1 installation doesn't help.

**Comment by JeffersonPark1304** [comment]
@lyang556 how did you solve your issue? Can you elaborate?

**Comment by Lyang556** [comment]
@JeffersonPark1304 I run the  rf_diffusion_all_atom in a conda enviroment , and you can find the conda YAML file in https://github.com/ikalvet/heme_binder_diffusion/blob/main/envs/diffusion.yml
