### ISSUE TITLE
Incorrect link in the Science article

### ISSUE THREAD

**Issue by gamazeps** [baker-laboratory/rf_diffusion_all_atom#3]
Hi !

First of all, thanks a lot for making this software available, it's amazing that you did !

A quick note on the fact that the [Science](https://www.science.org/doi/10.1126/science.adl2528) article incorrectly links to https://github.com/baker-laboratory/rf_diffusion_aa_public/ instead of this repository, I don't know if you can ask Science to correct that typo ;)

Cheers,
Felix

**Comment by ikalvet** [comment]
Thank you! We also noticed that immediately after publishing and asked the editors to fix it.
