### ISSUE TITLE
Question About Sequence Design Evaluation

### ISSUE THREAD

**Issue by warriors44** [baker-laboratory/rf_diffusion_all_atom#8]
Hello, and thank you for developing such useful software. 

I'm not sure if this is the appropriate place to ask, but I have a simple question regarding the design method described in your paper, specifically about the use of RFdiffusion-AA. After designing sequences with Ligand/ProteinMPNN, I noticed that RoseTTAfold-AA was not utilized to evaluate the validity of these sequences. Is this because you believe that the Rosetta relax and the AF2 method provide a more reliable evaluation?

Thank you.

**Comment by ikalvet** [comment]
We used AlphaFold2 to have an independent evaluation of the sequences, so that the selection process wouldn't be biased by the method that produced the backbones.

**Comment by warriors44** [comment]
I see. That makes sence. Thank you.

**Comment by warriors44** [comment]
I see. That makes sense. Thank you.
